image: node:12.13.0
on: push
jobs:
  
  build:
    runs-on: ubuntu-latest
    name: setup
    steps:
      run:
        - npm ci --no-optional
      artifacts:
        - node_modules/**
      run:
        - npm run build
      run:
        - npm run test
      
  cypress:
    name: cypress tests
    runs-on: cypress/included:3.8.3
    steps:
      run:
        - npm run test:e2e:ci
  visual test:       
    name: visual tests
    runs-on: cypress/included:3.8.3
    steps:
      run:
        - npm run test:visual:ci
      artifacts:
      - cypress/screenshots/**
      - cypress/snapshots/**
